###

# curl 'https://temporarymail.com/ajax/?action=getEmail&value=6AuCKLpAqg5BIVxI0YFNM9QighHMecS3' 
#  -X 'POST' 
#  -H 'authority: temporarymail.com' 
#  -H 'accept: */*' 
#  -H 'accept-language: en-US,en;q=0.9' 
#  -H 'content-length: 0' 
#  -H 'cookie: __gads=ID=04c76807a73be696-220c20e04e7f0050:T=1668355914:RT=1668355914:S=ALNI_MYK7uUCQkEvxVEUoeVQfshgsJ9Bhg; __gpi=UID=000009d83428c28c:T=1668355914:RT=1668355914:S=ALNI_MbJ1n1LpVGgfYY15IgX4N92MGIpPA' 
#  -H 'origin: https://temporarymail.com' 
#  -H 'referer: https://temporarymail.com/' 
#  -H 'sec-ch-ua: "Google Chrome";v="107", "Chromium";v="107", "Not=A?Brand";v="24"' 
#  -H 'sec-ch-ua-mobile: ?0' 
#  -H 'sec-ch-ua-platform: "macOS"' 
#  -H 'sec-fetch-dest: empty' 
#  -H 'sec-fetch-mode: cors' 
#  -H 'sec-fetch-site: same-origin' 
#  -H 'user-agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36' 
#  -H 'x-requested-with: XMLHttpRequest' 
#  --compressed
POST https://temporarymail.com/ajax/?action=getEmail&value=6AuCKLpAqg5BIVxI0YFNM9QighHMecS3
authority: temporarymail.com
accept: */*
accept-language: en-US,en;q=0.9
content-length: 0
user-agent: some
x-requested-with: XMLHttpRequest

###

